### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by AnHoff** [Interacao-Humano-Computador/2022.2-SimplesNacional#4]
# Descrição
Criação da página inicial do GitHub Pages.

# Tarefas
- [x] Apresentação dos integrantes
- [x] Descrição básica sobre o projeto

# Critérios de aceitação
- [x] A página apresenta as informações conforme desejado.

**Comment by VasconcelosJoao** [comment]
Criação da pagina Home e edição da paleta de cores da pagina do github pages
